// Copyright (c) 2016, XMOS Ltd, All rights reserved

#include "xcore_c_port_impl.h"
extern void _port_setc(port p, uint32_t c);
extern void _port_set_transfer_width(port p, int width);
extern port _port_alloc(int port_id);
extern void _port_reset(port p);
extern void _port_free(port p);
extern void _port_set_buffered(port p);
extern void _port_set_unbuffered(port p);
extern void _port_set_clock(port p, clock clk);
extern void _port_set_inout_data(port p);
extern void _port_set_out_clock(port p);
extern void _port_set_out_ready(port p, port ready_source);
extern void _port_set_invert(port p);
extern void _port_set_no_invert(port p);
extern void _port_set_sample_falling_edge(port p);
extern void _port_set_sample_rising_edge(port p);
extern void _port_set_master(port p);
extern void _port_set_slave(port p);
extern void _port_set_no_ready(port p);
extern void _port_set_ready_strobed(port p);
extern void _port_set_ready_handshake(port p);
extern int16_t _port_get_trigger_time(port p);
extern void _port_set_trigger_time(port p, int16_t t);
extern void _port_clear_trigger_time(port p);
extern void _port_set_trigger_in_equal(port p, int d);
extern void _port_set_trigger_in_not_equal(port p, int d);
extern void _port_clear_trigger_in(port p);
extern int _port_peek(port p);
extern void _port_out(port p, int data);
extern int _port_in(port p);
extern void _port_out_shift_right(port p, int *data);
extern void _port_in_shift_right(port p, int *data);
extern int _port_endin(port p);
extern void _port_clear_buffer(port p);

#include "xcore_c_port.h"
extern xcore_c_error port_alloc(port *p, int port_id);
extern xcore_c_error port_reset(port p);
extern xcore_c_error port_alloc_buffered(port *p, int port_id, int transfer_width);
extern xcore_c_error port_free(port *p);
extern xcore_c_error port_set_transfer_width(port p, int transfer_width);
extern xcore_c_error port_set_buffered(port p);
extern xcore_c_error port_set_unbuffered(port p);
extern xcore_c_error port_set_clock(port p, clock clk);
extern xcore_c_error port_set_inout_data(port p);
extern xcore_c_error port_set_out_clock(port p);
extern xcore_c_error port_set_out_ready(port p, port ready_source);
extern xcore_c_error port_set_invert(port p);
extern xcore_c_error port_set_no_invert(port p);
extern xcore_c_error port_set_sample_falling_edge(port p);
extern xcore_c_error port_set_sample_rising_edge(port p);
extern xcore_c_error port_set_master(port p);
extern xcore_c_error port_set_slave(port p);
extern xcore_c_error port_set_no_ready(port p);
extern xcore_c_error port_set_ready_strobed(port p);
extern xcore_c_error port_set_ready_handshake(port p);
extern xcore_c_error port_get_trigger_time(port p, int16_t *ts);
extern xcore_c_error port_set_trigger_time(port p, int16_t count);
extern xcore_c_error port_clear_trigger_time(port p);
extern xcore_c_error port_set_trigger_in_equal(port p, int v);
extern xcore_c_error port_set_trigger_in_not_equal(port p, int v);
extern xcore_c_error port_clear_trigger_in(port p);
extern xcore_c_error port_peek(port p, int *data);
extern xcore_c_error port_out(port p, int data);
extern xcore_c_error port_in(port p, int *data);
extern xcore_c_error port_out_shift_right(port p, int *data);
extern xcore_c_error port_in_shift_right(port p, int *data);
extern xcore_c_error port_out_at_time(port p, int16_t t, int data);
extern xcore_c_error port_in_at_time(port p, int16_t t, int *data);
extern xcore_c_error port_out_shift_right_at_time(port p, int16_t t, int *data);
extern xcore_c_error port_in_shift_right_at_time(port p, int16_t t, int *data);
extern xcore_c_error port_in_when_pinseq(port p, port_type_t pt, int value, int *data);
extern xcore_c_error port_in_when_pinsneq(port p, port_type_t pt, int value, int *data);
extern xcore_c_error port_in_shift_right_when_pinseq(port p, port_type_t pt, int value, int *data);
extern xcore_c_error port_in_shift_right_when_pinsneq(port p, port_type_t pt, int value, int *data);
extern xcore_c_error port_clear_buffer(port p);
extern xcore_c_error port_endin(port p, int *num);
extern xcore_c_error port_force_input(port p, int *num, int *data);
extern xcore_c_error port_setup_select(port p, unsigned enum_id);
extern xcore_c_error port_setup_select_callback(port p, void *data, select_callback func);
extern xcore_c_error port_setup_interrupt_callback(port p, void *data, interrupt_callback func);
extern xcore_c_error port_enable_trigger(port p);
extern xcore_c_error port_disable_trigger(port p);

#include "xcore_c_port_protocol.h"
extern xcore_c_error port_protocol_in_handshake(port p, port readyin, port readyout, clock clk);
extern xcore_c_error port_protocol_out_handshake(port p, port readyin, port readyout, clock clk, unsigned initial);
extern xcore_c_error port_protocol_in_strobed_master(port p, port readyout, const clock clk);
extern xcore_c_error port_protocol_out_strobed_master(port p, port readyout, const clock clk, unsigned initial);
extern xcore_c_error port_protocol_in_strobed_slave(port p, port readyin, clock clk);
extern xcore_c_error port_protocol_out_strobed_slave(port p, port readyin, clock clk, unsigned initial);
